server:
  port: 8888

spring:
  application:
    name: gallery

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: ENC(1+OWZK54rRu0Pv5orMaz6Nhx+hj67oHSnm0Z43VR4FTmDKuPxfAaxHkMDvTGX390vkXSed+B1VScZiyMQSh/apc+VvpNAlnDvlhw8e6gbf6yb7dmrfcYzzlu0/Mdz/ni)
    username: ENC(ptgPiCGfwu1nCmkYDF/6XyGnp2Wcagax)
    password: ENC(8UNZPir3wjbMd+jGSXvrp7jFXY7ZgOfULqlgWB4zJdg=)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(RXaEtTItfS679Ihq2CWcSvrnqFd4Rt71jMWTLYoVaXGSIx4QrNoALUc5bBbKJsQA)
            redirect-uri: ENC(GaLdhQNWU0EKpnhlnXlpR9Jysm8zTTuTHfHIQkkMf5r69HUGJU/9wYRqpPanbOJj)
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#config:
#  import: bootstrap.yml

cloud:
  aws:
    s3:
      bucket: ENC(O7O9NN+RIl8p7GO0s/2PJhw3FvYTM/It)
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      accessKey: ENC(iR+LYe97Igzp3iiLij3PjEbiyUmWg/R0c2hFRtnMgXk=)
      secretKey: ENC(OXH6lj/RA4DRFJ8sBXI9siArzUmAAyoafjbcvy99uuROQuDBdor5aP0nTphSofzxhgjvYWRIm08=)
    stack:
      auto: false

jwt:
  secret: ENC(g5q/3DYd3/gKvvn+ObxcQsWdORr6dK6C3Nw/BxjjrNV2Lux+qUfpFgbgX7iOjXCyMqYYfpcw6bJ04gYZVi2renFnGQCAJPRCTDr2EQpUmWJ9j7fmM8jmiQUIorKfZoa65zlMLg7OgJNbA8ZfbyvYA4j+LADRI6XYQWvdXfJctxq9+SYKf17E/Xs1SmcVEHAyBev1uN6DqrK3Z8fGVSDkuY5CzF/ETTG2)
  accessTokenExpiration: ENC(3WIulzhNyf0kYojbECdk7Q==)
  refreshTokenExpiration: ENC(obqzP+FtPVU/lZS2X3sMHprSlS31Ou0t)

email:
  gmail:
    id: ENC(OkKaQd4UnXslSaKPJ4SwMMYm2lUPmHH9piqwvipdQ7g=)
    pw: ENC(KlbvlVSus+RvVsHq5EMKuaL+YdEkQ/vxdyI/dn4c6n0=)
  naver:
    id: ENC(UQs859awPt7sKp69E/8nSfPC5tYedJlk2NGAT7EYzEY=)
    pw: ENC(dd8+VY2qXOOt9Lll+wZelyzL3rjIAOyJ)

github:
  apiUrl_front: https://api.github.com/repos/potato-club/dessert-gallery-front/issues
  apiUrl_back: https://api.github.com/repos/potato-club/dessert-gallery-back/issues
  secret:
    back: ENC(4IR5kq9OFnTn1xHoGmJVoe5Gd3X7VbJnSImCh4nuB1RBxQ61fm2tWViNIj//usHSgFvf4mXesYs=)
    front_y: ENC(UkT2r01WfATpE8rieOI61aw8kZ/O51h6EeFybzp1F6XvmkU9sH+HJlxahAECXwmc6/mlCN78Yow=)
    front_d: ENC(NcHnat6lhnoL2Mi7b+zNFeyPz6w5Q8xtQj9JPT3gR3tve5dVIBTne5A/JM4yADIKKqGkuL92R48=)
    front_j: ENC(eF1XPee8PBNjqEr8UVTDNxAwv4uEFJsB4nZ28j1lUnttj/sNqgNya5QKiJJqVdqDUR58LT01nXU=)

management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh, info, metrics, prometheus

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

viewCount:
  key: updateView